INSERT INTO ACCOUNT (ID, USERNAME, PASSWORD,STUDENTID ,HASOUTSTANDINGBALANCE) VALUES (1, 'testuser1', 'testpassword','c1234567',false);
INSERT INTO ACCOUNT (ID, USERNAME, PASSWORD,STUDENTID ,HASOUTSTANDINGBALANCE) VALUES (2, 'testuser2', 'testpassword','c1234568',false);
INSERT INTO COURSE(ID, TITLE, DESCRIPTION, FEE) VALUES (1,'testcourse1', 'test description', 20.00);
INSERT INTO COURSE(ID, TITLE, DESCRIPTION, FEE) VALUES (2,'testcourse2', 'test description', 20.00);
INSERT INTO COURSE(ID, TITLE, DESCRIPTION, FEE) VALUES (3,'testcourse3', 'test description', 20.00);